# build_client.py
import PyInstaller.__main__
import os
import shutil
import playwright
from dotenv import dotenv_values

# Read current .env
env_config = dotenv_values(".env")
print(f"Loaded environment for baking: {env_config}")

# Inject into core/build_config.py
build_config_path = "core/build_config.py"
original_build_config = ""
if os.path.exists(build_config_path):
    with open(build_config_path, "r", encoding="utf-8") as f:
        original_build_config = f.read()

# Generate baked config content
# We only bake specific keys to avoid leaking sensitive dev secrets if not intended
KEYS_TO_BAKE = ["GEO_SERVER_URL", "RPA_HEADLESS", "POLL_INTERVAL"]
baked_data = {k: env_config.get(k) for k in KEYS_TO_BAKE if env_config.get(k)}

# Always fallback to default prod URL if missing in .env
if not baked_data.get("GEO_SERVER_URL"):
     # Default to local dev server for open source build
     baked_data["GEO_SERVER_URL"] = "http://localhost:8002/api/v1"

with open(build_config_path, "w", encoding="utf-8") as f:
    f.write(f"# Auto-generated by build_client.py\n")
    f.write(f"BAKED_CONFIG = {repr(baked_data)}\n")

print(f"Baking config into EXE: {baked_data}")

# 0. Locate Playwright Driver
from pathlib import Path
playwright_root = Path(os.path.dirname(playwright.__file__))
# In newer pip versions, driver is inside `playwright/driver`
# We need to preserve the `playwright/driver` structure in the temporary directory
pw_driver_src = playwright_root / "driver"

print(f"Playwright location: {playwright_root}")
print(f"Embedding Driver from: {pw_driver_src}")

# 1. 确保已安装 PyInstaller
print("Starting build process...")

# 2. 清理旧构建
if os.path.exists("dist"):
    shutil.rmtree("dist")
if os.path.exists("build"):
    shutil.rmtree("build")

# 3. 运行打包
# 如果代码中有动态导入（如 handlers），可能需要 hidden-import
PyInstaller.__main__.run([
    'worker_main.py',
    '--name=DigitalEmployeeRPA',
    '--onefile', # 单文件 EXE 更方便分发
    '--console', # 保留控制台窗口（这是RPA，用户喜欢看到日志在跑）
    '--icon=../../apps/web-console/public/favicon.ico', # 假设有图标
    
    # CRITICAL: Manually embed Playwright driver 
    # Source inside site-packages -> Destination 'playwright/driver' inside bundle
    f'--add-data={pw_driver_src}{os.pathsep}playwright/driver',

    '--hidden-import=handlers.base_handler',
    '--hidden-import=handlers.media_handler',
    '--hidden-import=handlers.zhihu_handler',
    '--hidden-import=handlers.baike_handler',
    '--hidden-import=handlers.social_platform_handler',
    '--hidden-import=playwright',
    
    # Exclude unnecessary heavy libraries to avoid conflicts and reduce size
    '--exclude-module=PyQt5',
    '--exclude-module=PySide6',
    '--exclude-module=tkinter',
    '--exclude-module=matplotlib',
    '--exclude-module=IPython',
    '--exclude-module=numpy',
    '--exclude-module=scipy',
    '--exclude-module=pandas',
    
    # 注意：Playwright 的浏览器二进制文件通常不会被打包进去，
    # 第一次运行可能会提示缺少浏览器。
    # 更好的做法是在 EXE 启动时检查并在本地 install
])

# Restore original build_config.py
with open(build_config_path, "w", encoding="utf-8") as f:
    f.write(original_build_config)
print("Restored core/build_config.py to original state.")

print("Build complete! Check the 'dist' folder.")

# 4. Copy to Web Console public downloads
import shutil
target_dir = "../../apps/web-console/public/downloads"
if not os.path.exists(target_dir):
    os.makedirs(target_dir)

src = "dist/DigitalEmployeeRPA.exe"
dst = os.path.join(target_dir, "DigitalEmployeeRPA.exe")

if os.path.exists(src):
    shutil.copy2(src, dst)
    print(f"✅ Successfully deployed to: {dst}")
else:
    print(f"❌ Error: Source file not found: {src}")
